### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by kirAn-sAi** [rawho/flipkart-scraper#8]
I have ran the script by supplying iphone as a product it is not resulting any records in the CSV file 

I have tried the same for galaxy note 10 plus also. The same happened
![16025215535631681233308128827858](https://user-images.githubusercontent.com/30194836/95771917-84c6f500-0cd9-11eb-97a0-cc88e3d699f2.jpg)

**Comment by rawho** [comment]
Have you changed any code in the python file
I had tried now, i am getting the results in csv file
![Screenshot from 2020-10-13 01-29-30](https://user-images.githubusercontent.com/67005725/95785553-9ae1af00-0cf3-11eb-9b92-40f43d2cb3fb.png)

**Comment by rawho** [comment]
> I have ran the script by supplying iphone as a product it is not resulting any records in the CSV file
> 
> I have tried the same for galaxy note 10 plus also. The same happened
> ![16025215535631681233308128827858](https://user-images.githubusercontent.com/30194836/95771917-84c6f500-0cd9-11eb-97a0-cc88e3d699f2.jpg)

any updates. Do you get it

**Comment by kirAn-sAi** [comment]
I got what happened. 

Initially I have searched for **galaxy note 10 plus** it doesn't returned any products. This time I have supplied filename as **my_search**

So only header components written to file.

The I searched for iphone this time I have supplied filename as **my_search.csv** 

The contents were written to **my_search.csv.csv** file

I'm searching contents in **my_search.csv** file that's why I didn't get the product details.


I think it is better to ignore adding file extension if user already supplied.

**Comment by rawho** [comment]
> I got what happened.
> 
> Initially I have searched for **galaxy note 10 plus** it doesn't returned any products. This time I have supplied filename as **my_search**
> 
> So only header components written to file.
> 
> The I searched for iphone this time I have supplied filename as **my_search.csv**
> 
> The contents were written to **my_search.csv.csv** file
> 
> I'm searching contents in **my_search.csv** file that's why I didn't get the product details.
> 
> I think it is better to ignore adding file extension if user already supplied.

Yeah sure i will update it
